// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VyShare;

namespace VyShare.Migrations
{
    [DbContext(typeof(VyShareContext))]
    partial class VyShareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("VyShare.Models.BasicTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndPoint")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seat")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPoint")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TicketHolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TicketHolderId");

                    b.ToTable("BasicTickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b888c59c-5556-43f3-a57b-5dcfb2458990"),
                            EndPoint = "Grønnåsen Skole",
                            OrderId = new Guid("486c460b-dbae-4a5a-a3ef-fb9e94e1ff4d"),
                            Price = 412m,
                            ReferenceCode = "YXHA5",
                            Seat = "13A",
                            StartPoint = "Volda",
                            TicketHolderId = new Guid("64eca478-593b-40d6-8785-dcf4322cbabf"),
                            Type = "Honnør"
                        },
                        new
                        {
                            Id = new Guid("70189d4e-0a16-4370-b0e5-789b02d25fcf"),
                            EndPoint = "Grønnåsen Skole",
                            OrderId = new Guid("486c460b-dbae-4a5a-a3ef-fb9e94e1ff4d"),
                            Price = 375m,
                            ReferenceCode = "YXHBA6",
                            Seat = "13B",
                            StartPoint = "Volda",
                            TicketHolderId = new Guid("f4f86a47-e9a5-49b4-b187-745e6c0bbadb"),
                            Type = "Student"
                        },
                        new
                        {
                            Id = new Guid("80c634d7-cde3-49ab-878d-db06b6a9ea27"),
                            EndPoint = "Ullevål stadion",
                            OrderId = new Guid("0f76be9e-6181-4b0f-bd24-0749204e7d39"),
                            Price = 199m,
                            ReferenceCode = "OPS34",
                            Seat = "03A",
                            StartPoint = "Sandefjord",
                            TicketHolderId = new Guid("865f6842-4fba-4cc7-b556-53bc6323b7b5"),
                            Type = "Student"
                        },
                        new
                        {
                            Id = new Guid("210f3066-29da-4506-81aa-71e1bdc3351c"),
                            EndPoint = "Ullevål stadion",
                            OrderId = new Guid("0f76be9e-6181-4b0f-bd24-0749204e7d39"),
                            Price = 199m,
                            ReferenceCode = "PSD33",
                            Seat = "03B",
                            StartPoint = "Sandefjord",
                            TicketHolderId = new Guid("42dce654-7c54-44fd-b26d-ef4a3e469acf"),
                            Type = "Student"
                        },
                        new
                        {
                            Id = new Guid("bedf6391-e36a-4a41-b2a2-fdf61028524c"),
                            EndPoint = "Ullevål stadion",
                            OrderId = new Guid("0f76be9e-6181-4b0f-bd24-0749204e7d39"),
                            Price = 219m,
                            ReferenceCode = "QSO20",
                            Seat = "03C",
                            StartPoint = "Larvik",
                            TicketHolderId = new Guid("e3476b88-c484-426b-aeeb-aab2de097dc3"),
                            Type = "Student"
                        });
                });

            modelBuilder.Entity("VyShare.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("486c460b-dbae-4a5a-a3ef-fb9e94e1ff4d"),
                            Name = "Familietur til Grønnåsen 15.06.20"
                        },
                        new
                        {
                            Id = new Guid("0f76be9e-6181-4b0f-bd24-0749204e7d39"),
                            Name = "Fotballkamp"
                        });
                });

            modelBuilder.Entity("VyShare.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("VyShare.Models.Contact", b =>
                {
                    b.HasBaseType("VyShare.Models.Person");

                    b.HasDiscriminator().HasValue("Contact");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64eca478-593b-40d6-8785-dcf4322cbabf"),
                            Email = "katofje@online.no",
                            FirstName = "Kato",
                            LastName = "Fjellberg",
                            PhoneNumber = "90125872"
                        },
                        new
                        {
                            Id = new Guid("f4f86a47-e9a5-49b4-b187-745e6c0bbadb"),
                            Email = "kathi95@gmail.com",
                            FirstName = "Kathrine",
                            LastName = "Wesenlund",
                            PhoneNumber = "40912854"
                        },
                        new
                        {
                            Id = new Guid("865f6842-4fba-4cc7-b556-53bc6323b7b5"),
                            Email = "kk@realitytv.com",
                            FirstName = "Kim",
                            LastName = "Kardashian",
                            PhoneNumber = "92304215"
                        },
                        new
                        {
                            Id = new Guid("42dce654-7c54-44fd-b26d-ef4a3e469acf"),
                            Email = "karefje@online.no",
                            FirstName = "Kåre",
                            LastName = "Fjellberg",
                            PhoneNumber = "90002390"
                        },
                        new
                        {
                            Id = new Guid("e3476b88-c484-426b-aeeb-aab2de097dc3"),
                            Email = "kennekennern51@outlook.com",
                            FirstName = "Kenneth",
                            LastName = "Kennesen",
                            PhoneNumber = "40534009"
                        });
                });

            modelBuilder.Entity("VyShare.Models.User", b =>
                {
                    b.HasBaseType("VyShare.Models.Person");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a384222a-89fa-4ac9-a60c-731814bc2732"),
                            Email = "popokatepetl@online.no",
                            FirstName = "Pål",
                            LastName = "Fjellberg",
                            PhoneNumber = "90035412",
                            Username = "popokatepetl"
                        },
                        new
                        {
                            Id = new Guid("6a50184a-c3db-46bc-9990-ae8e3b35c899"),
                            Email = "marmelade86@gmail.com",
                            FirstName = "Mia",
                            LastName = "Mikkelsen",
                            PhoneNumber = "45612039",
                            Username = "marmelade86"
                        });
                });

            modelBuilder.Entity("VyShare.Models.BasicTicket", b =>
                {
                    b.HasOne("VyShare.Models.Order", null)
                        .WithMany("BasicTickets")
                        .HasForeignKey("OrderId");

                    b.HasOne("VyShare.Models.Person", "TicketHolder")
                        .WithMany()
                        .HasForeignKey("TicketHolderId");
                });

            modelBuilder.Entity("VyShare.Models.Order", b =>
                {
                    b.HasOne("VyShare.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
